name: Deploy Application

on:
  push:
    branches:
      - prod

env:
  APP_ENV: deployment

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Configure PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: ctype, curl, DOM, fileinfo, filter, hash, json, mbstring, openssl, PCRE, PDO, session, tokenizer, xml

      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate frontend routes file
        env:
          APP_URL: http://${{ vars.HOST_IP }}
        run: |
          php artisan ziggy:generate

      - name: Compile CSS and Javascript
        run: |
          pnpm build

      - name: Create deployment artifact
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=tests --exclude=storage *

      - name: Store artifact for distribution
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: ${{ github.sha }}.tar.gz

  prepare-release-on-server:
    name: Prepare release
    runs-on: ubuntu-latest
    needs: create-deployment-artifacts
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-build

      - name: Upload
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: --mkPath
          path: ${{ github.sha }}.tar.gz
          remote_path: ${{ vars.HOST_PATH }}/artifacts
          remote_host: ${{ vars.HOST_IP }}
          remote_user: ${{ secrets.HOST_USER }}
          remote_key: ${{ secrets.HOST_KEY }}

      - name: Extract archive and create directories
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${{ vars.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_KEY }}
          envs: GITHUB_SHA
          script: |
            mkdir -p ${{ vars.HOST_PATH }}/{current,releases}
            mkdir -p ${{ vars.HOST_PATH }}/releases/${GITHUB_SHA}
            tar -xzf ${{ vars.HOST_PATH }}/artifacts/${GITHUB_SHA}.tar.gz -C "${{ vars.HOST_PATH}}/releases/${GITHUB_SHA}"
            rm -rf ${{ vars.HOST_PATH }}/releases/${GITHUB_SHA}/storage
            mkdir -p ${{ vars.HOST_PATH }}/storage/{app,public,framework,logs}
            mkdir -p ${{ vars.HOST_PATH }}/storage/framework/{cache,sessions,testing,views}
            sudo chmod -R 0777 ${{ vars.HOST_PATH }}/storage

  run-before-hooks:
    name: Before hook
    runs-on: ubuntu-latest
    needs: [ create-deployment-artifacts, prepare-release-on-server ]
    steps:
      - name: Run before hooks
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
          BASE_PATH: ${{ vars.HOST_PATH }}
          RELEASE_PATH: ${{ vars.HOST_PATH }}/releases/${{ github.sha }}
          ACTIVE_RELEASE_PATH: ${{ vars.HOST_PATH }}/current
          STORAGE_PATH: ${{ vars.HOST_PATH }}/storage
        with:
          host: ${{ vars.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_KEY }}
          envs: GITHUB_SHA, BASE_PATH, RELEASE_PATH, ACTIVE_RELEASE_PATH, STORAGE_PATH
          script: |
            cd $ACTIVE_RELEASE_PATH
            php artisan migrate --force

  activate-release:
    name: Activate release
    runs-on: ubuntu-latest
    needs: [ create-deployment-artifacts, prepare-release-on-server, run-before-hooks ]
    steps:
      - name: Activate release
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
          RELEASE_PATH: ${{ vars.HOST_PATH }}/releases/${{ github.sha }}
          ACTIVE_RELEASE_PATH: ${{ vars.HOST_PATH }}/current
          STORAGE_PATH: ${{ vars.HOST_PATH }}/storage
          BASE_PATH: ${{ vars.HOST_PATH }}
        with:
          host: ${{ vars.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_KEY }}
          envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH,ENV_PATH,LARAVEL_ENV
          script: |
            cd $RELEASE_PATH
            LARAVEL_ENV_ENCRYPTION_KEY="$(echo /run/secrets/ENV_KEY)" php artisan env:decrypt --env=prod
            ln -s -f $STORAGE_PATH $RELEASE_PATH
            ln -s -n -f $RELEASE_PATH $ACTIVE_RELEASE_PATH
            sudo systemctl reload phpfpm-abidan.service

  run-after-hooks:
    name: After hook
    runs-on: ubuntu-latest
    needs: [ create-deployment-artifacts, prepare-release-on-server, run-before-hooks, activate-release ]
    steps:
      - name: Run after hooks
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
          RELEASE_PATH: ${{ vars.HOST_PATH }}/releases/${{ github.sha }}
          ACTIVE_RELEASE_PATH: ${{ vars.HOST_PATH }}/current
          STORAGE_PATH: ${{ vars.HOST_PATH }}/storage
          BASE_PATH: ${{ vars.HOST_PATH }}
        with:
          host: ${{ vars.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_KEY }}
          envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH,ENV_PATH
          script: |
            cd $ACTIVE_RELEASE_PATH
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan inertia:stop-ssr

  clean-up:
    name: Clean up
    runs-on: ubuntu-latest
    needs: [ create-deployment-artifacts, prepare-release-on-server, run-before-hooks, activate-release, run-after-hooks ]
    steps:
      - name: Removing old releases and artifacts
        uses: appleboy/ssh-action@master
        env:
          RELEASES_PATH: ${{ vars.HOST_PATH }}/releases
          ARTIFACTS_PATH: ${{ vars.HOST_PATH }}/artifacts
        with:
          host: ${{ vars.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_KEY }}
          envs: RELEASES_PATH,ARTIFACTS_PATH
          script: |
            cd $RELEASE_PATH && ls -t -1 | tail -n +5 | xargs rm -rf
            cd $ARTIFACTS_PATH && ls -t -1 | tail -n +5 | xargs rm -rf
